# -*- coding: utf-8 -*-
"""baltimore_qml_kernel

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WNlkbv2hc-jrIHUSkihQf6L4pbAkdb84
"""

# `baltimore_qml_kernel.py` addresses the "Representation" research goal of the
# thesis. While the previous scripts focused on predicting exact pollution numbers
# (Regression), this script investigates whether a Quantum Kernel can identify
# structural differences between "High Pollution" and "Low Pollution" areas
# (Classification). By visualizing the Kernel Gram Matrix, we can see if the
# quantum feature map is successfully separating the data in a high-dimensional
# quantum state.

from utils import prepare_baltimore_qml_data
import numpy as np
import matplotlib.pyplot as plt
import os
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay

# Qiskit Imports
from qiskit.circuit.library import ZZFeatureMap
from qiskit_machine_learning.kernels import FidelityQuantumKernel

def run_quantum_kernel_classification():
    print("--- Setting up Quantum Kernel Classification (High vs Low Pollution) ---")

    # Ensure the output directory exists before attempting to save figures.
    os.makedirs("baltimore-figures", exist_ok=True)

    # 1. Prepare Data.
    X, y_continuous, _ = prepare_baltimore_qml_data()

    # Convert the continuous NO2 levels into a Binary Classification problem.
    # We use the median NO2 level as the threshold. Blocks above the median are
    # "High Pollution" (1), and those below are "Low Pollution" (0).
    median_no2 = np.median(y_continuous)
    y_binary = np.where(y_continuous > median_no2, 1, 0)

    print(f"Binary Threshold (Median NO2): {median_no2:.2f} ppb")

    # Scale Data. Quantum rotation gates expect inputs between 0 and 2pi to
    # fully utilize the Hilbert space.
    scaler = MinMaxScaler(feature_range=(0, 2*np.pi))
    X_scaled = scaler.fit_transform(X)

    # 2. Random Sampling.
    # Calculating a Quantum Kernel is computationally expensive (O(N^2)). For
    # this thesis demonstration, we take a random subset of 50 samples. We use a
    # fixed random seed to ensuring this subset is reproducible and not biased
    # by spatial ordering in the original file.
    rng = np.random.RandomState(42)
    indices = rng.choice(len(X_scaled), size=50, replace=False)
    X_subset = X_scaled[indices]
    y_subset = y_binary[indices]

    # Split this subset into training and testing.
    X_train, X_test, y_train, y_test = train_test_split(
        X_subset, y_subset, test_size=0.2, random_state=42, stratify=y_subset
    )

    # 3. Define the Quantum Kernel.
    # We use the `ZZFeatureMap` again. In the context of Kernels, this map takes
    # two data points, encodes them into quantum states, and computes their
    # "similarity" (inner product) in the high-dimensional quantum space.
    print("Building Quantum Kernel...")
    feature_map = ZZFeatureMap(feature_dimension=X.shape[1], reps=2, entanglement='linear')
    q_kernel = FidelityQuantumKernel(feature_map=feature_map)

    # 4. Train Quantum SVM.
    # We use a classical Support Vector Machine (SVC), but instead of a standard
    # radial basis function (RBF) kernel, we pass our custom quantum kernel.
    print("Training SVC with Quantum Kernel (this calculates the kernel matrix)...")
    qsvc = SVC(kernel=q_kernel.evaluate)
    qsvc.fit(X_train, y_train)

    # 5. Evaluate Performance.
    y_pred = qsvc.predict(X_test)
    print("\nQuantum Kernel Classification Report:")
    print(classification_report(y_test, y_pred))

    # 6. Visualization 1: Confusion Matrix.
    # This shows how often the model correctly identified High vs Low pollution.
    cm = confusion_matrix(y_test, y_pred)
    disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=["Low", "High"])
    disp.plot(cmap='Blues')
    plt.title("Quantum Kernel SVM: Confusion Matrix")
    plt.savefig("baltimore-figures/figure-quantum-kernel-cm.png", dpi=300)
    print("Saved: figure-quantum-kernel-cm.png")

    # 7. Visualization 2: The Gram Matrix.
    # This is the critical visualization for the "Representation" research question.
    # It visualizes the kernel matrix itself. Distinct patterns (blocks or gradients)
    # in this matrix indicate that the quantum feature map is successfully identifying
    # structure and separability in the data.
    print("Computing full Kernel Gram Matrix for visualization...")
    matrix_train = q_kernel.evaluate(X_train)

    plt.figure(figsize=(8, 6))
    plt.imshow(matrix_train, interpolation='nearest', origin='upper', cmap='viridis')
    plt.colorbar(label='Kernel Value (Fidelity)')
    plt.title("Quantum Kernel Gram Matrix\n(Visualizing Feature Separability)")
    plt.xlabel("Training Sample Index")
    plt.ylabel("Training Sample Index")
    plt.savefig("baltimore-figures/figure-quantum-kernel-gram.png", dpi=300)
    print("Saved: figure-quantum-kernel-gram.png")

if __name__ == "__main__":
    run_quantum_kernel_classification()