# -*- coding: utf-8 -*-
"""baltimore_comparison

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WNlkbv2hc-jrIHUSkihQf6L4pbAkdb84
"""

# `baltimore_comparison.py` acts as the synthesis engine for the thesis results.
# It runs both the classical baselines (Linear Regression, Random Forest) and
# the Quantum Variational Regressor (VQR), aggregates their performance metrics,
# and generates a unified comparison table. This table is the key artifact for
# evaluating the "Performance" research question.

from utils import prepare_baltimore_qml_data
from baltimore_ml import train_classical_models
from baltimore_qml import train_baltimore_qml_regressor
import matplotlib.pyplot as plt
import pandas as pd
import os
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

def generate_master_table():
    print("--- Generating Master Comparison Table ---")

    # 1. Get Data. We use the shared utility to ensure all models see the exact
    # same dataset.
    X, y, _ = prepare_baltimore_qml_data()

    # 2. Run Classical Models. We force `random_state=42` to ensure the train/test
    # split is deterministic.
    results_ml, _, _ = train_classical_models(X, y, random_state=42)

    # 3. Run Quantum Model. We use the same random state. Note that we rely on
    # `train_baltimore_qml_regressor` to handle the scaling internally, but
    # since the random seed is identical, the split indices will match.
    print("\n--- Retrieving Quantum VQR Metrics ---")
    _, _, _, _, _, y_pred_q = train_baltimore_qml_regressor(X, y, maxiter=300, random_state=42)

    # We retrieve the actual test values (`y_test`) from the classical results.
    # Because of the shared random seed, these are guaranteed to match the
    # target values used in the quantum prediction.
    y_test = results_ml['linear_regression']['y_test']

    # Calculate standard metrics for the Quantum model.
    mse_q = mean_squared_error(y_test, y_pred_q)
    r2_q = r2_score(y_test, y_pred_q)
    mae_q = mean_absolute_error(y_test, y_pred_q)

    # 4. Build a Pandas DataFrame to organize the results.
    data = {
        "Model": ["Linear Regression", "Random Forest", "Quantum VQR"],
        "MSE": [
            results_ml['linear_regression']['mse'],
            results_ml['random_forest']['mse'],
            mse_q
        ],
        "R2 Score": [
            results_ml['linear_regression']['r2'],
            results_ml['random_forest']['r2'],
            r2_q
        ],
        "MAE": [
            results_ml['linear_regression']['mae'],
            results_ml['random_forest']['mae'],
            mae_q
        ]
    }

    df_results = pd.DataFrame(data)

    # 5. Render the table as a high-resolution image for inclusion in the thesis document.
    os.makedirs("baltimore-figures", exist_ok=True)
    fig, ax = plt.subplots(figsize=(10, 3))
    ax.axis('tight')
    ax.axis('off')

    # Format the numbers to 4 decimal places for scientific precision.
    cell_text = []
    for i in range(len(df_results)):
        row = df_results.iloc[i]
        cell_text.append([
            row['Model'],
            f"{row['MSE']:.4f}",
            f"{row['R2 Score']:.4f}",
            f"{row['MAE']:.4f}"
        ])

    table = ax.table(cellText=cell_text, colLabels=["Model", "MSE", "R² Score", "MAE"],
                     loc='center', cellLoc='center')

    table.auto_set_font_size(False)
    table.set_fontsize(11)
    table.scale(1, 2)

    # Color the headers to match the aesthetic of previous figures.
    for i in range(4):
        table[(0, i)].set_facecolor('#4472C4')
        table[(0, i)].set_text_props(color='white', weight='bold')

    plt.title("Thesis Comparison: Classical Baselines vs. Quantum VQR", weight='bold', pad=20)
    plt.savefig("baltimore-figures/final_comparison_table.png", dpi=300, bbox_inches='tight')
    print("Table saved to baltimore-figures/final_comparison_table.png")

if __name__ == "__main__":
    generate_master_table()