# -*- coding: utf-8 -*-
"""baltimore_qml

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WNlkbv2hc-jrIHUSkihQf6L4pbAkdb84
"""

# `baltimore_qml.py` represents the core innovation of this thesis: applying
# Quantum Machine Learning (QML) to the problem of environmental justice.
# Instead of classical algorithms, we employ a Variational Quantum Regressor
# (VQR) to learn the relationship between HOLC redlining grades and modern air
# pollution levels.

from utils import init, prepare_baltimore_qml_data

import os
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error, r2_score

# Qiskit imports: These libraries allow us to construct and simulate quantum
# circuits.
from qiskit.circuit.library import ZZFeatureMap, RealAmplitudes
from qiskit_machine_learning.algorithms import VQR
from qiskit_algorithms.optimizers import COBYLA
from qiskit.primitives import Estimator


# `train_baltimore_qml_regressor` defines the quantum training pipeline. It
# constructs a parameterized quantum circuit, encodes the classical data into
# quantum states, and optimizes the parameters to minimize prediction error.
def train_baltimore_qml_regressor(X, y, maxiter=300, test_size=0.2, random_state=42):
    """
    Train a Variational Quantum Regressor (VQR) to predict NO2 for Baltimore.

    Args:
        maxiter (int): The number of optimization steps. We use 300 to give
                       the COBYLA optimizer sufficient time to navigate the
                       complex energy landscape of the quantum circuit.

    Returns:
        vqr:       trained quantum model
        scaler_x:  feature scaler
        scaler_y:  target scaler
        X_test:    test features (scaled)
        y_test:    actual NO2 values (original scale)
        y_pred:    predicted NO2 values (original scale)
    """
    print("--- Preparing data for QML ---")

    # Quantum circuits (specifically rotation gates) generally operate best on
    # data normalized between 0 and 1 (or 0 and 2pi).
    scaler_x = MinMaxScaler()
    X_scaled = scaler_x.fit_transform(X)

    # We also scale the target variable to aid convergence.
    scaler_y = MinMaxScaler()
    y_scaled = scaler_y.fit_transform(y.reshape(-1, 1)).flatten()

    # Crucially, we use the same `random_state` (42) as the classical script.
    # This ensures an "apples-to-apples" comparison.
    X_train, X_test, y_train, y_test = train_test_split(
        X_scaled,
        y_scaled,
        test_size=test_size,
        random_state=random_state,
    )

    num_features = X.shape[1]

    print(f"Number of training samples: {len(X_train)}")
    print(f"Number of test samples:     {len(X_test)}")
    print(f"Number of features:         {num_features}")

    # The Feature Map is responsible for encoding classical data into the
    # quantum state. We choose the `ZZFeatureMap` because it creates entanglement
    # between qubits based on the products of different features. This allows the
    # model to inherently capture non-linear correlations between Race and Grade.
    feature_map = ZZFeatureMap(feature_dimension=num_features, reps=1)

    # The Ansatz is the trainable part of the circuit. `RealAmplitudes` is a
    # heuristic circuit that is relatively shallow, making it suitable for
    # current Noisy Intermediate-Scale Quantum (NISQ) simulations.
    ansatz = RealAmplitudes(num_qubits=num_features, reps=1)

    # We use the COBYLA optimizer, which is a gradient-free optimizer often
    # used in quantum computing because it is robust to noise.
    optimizer = COBYLA(maxiter=maxiter)

    # Instantiate the Regressor with our defined components.
    vqr = VQR(
        feature_map=feature_map,
        ansatz=ansatz,
        optimizer=optimizer,
        estimator=Estimator(),
    )

    print(f"--- Training Quantum Model (VQR) with {maxiter} iterations ---")
    print("Note: This may take several minutes depending on your CPU...")
    vqr.fit(X_train, y_train)

    # Generate predictions on the test set.
    y_pred_scaled = np.array(vqr.predict(X_test)).reshape(-1, 1)
    y_test_scaled = y_test.reshape(-1, 1)

    # Inverse-transform the predictions to get back to real NO2 units (ppb).
    y_pred = scaler_y.inverse_transform(y_pred_scaled)
    y_test_actual = scaler_y.inverse_transform(y_test_scaled)

    # Evaluate performance.
    mse = mean_squared_error(y_test_actual, y_pred)
    r2 = r2_score(y_test_actual, y_pred)

    print("QML Regression Results (Baltimore NO2):")
    print(f"  Mean Squared Error: {mse:.4f}")
    print(f"  R2 Score:           {r2:.4f}")

    return vqr, scaler_x, scaler_y, X_test, y_test_actual, y_pred


# `plot_baltimore_qml_results` visualizes the quantum model's predictions
# against the ground truth.
def plot_baltimore_qml_results(y_actual, y_pred, out_dir="baltimore-figures"):
    os.makedirs(out_dir, exist_ok=True)

    plt.figure(figsize=(8, 6))
    plt.scatter(y_actual, y_pred, color="royalblue", alpha=0.6, label="Census Blocks")

    # If the model were perfect, all points would fall on this red line.
    min_val = min(np.min(y_actual), np.min(y_pred))
    max_val = max(np.max(y_actual), np.max(y_pred))
    plt.plot([min_val, max_val], [min_val, max_val],
             "r--", linewidth=1.5, label="Perfect Prediction")

    plt.xlabel("Actual NO₂ (ppb)")
    plt.ylabel("Predicted NO₂ (ppb) – Quantum Model")
    plt.title("Baltimore: Quantum Regression of NO₂ from HOLC Grade & Demographics")
    plt.legend()
    plt.grid(True, alpha=0.3)

    out_path = os.path.join(out_dir, "figure-bqml-1.png")
    plt.savefig(out_path, dpi=300, bbox_inches="tight")
    plt.close()

    print(f"QML prediction plot saved to {out_path}")


if __name__ == "__main__":
    # 1. Load data using the shared utility function.
    X, y, baltimore_df = prepare_baltimore_qml_data()

    # 2. Train the Quantum Model.
    model, scaler_x, scaler_y, X_test, y_test, y_pred = train_baltimore_qml_regressor(X, y)

    # 3. Plot the results.
    plot_baltimore_qml_results(y_test, y_pred)