# -*- coding: utf-8 -*-
"""baltimore_depth_test

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q9eu4ErR6OhheQkwHyhC_m-27BUbLcW1
"""

# `baltimore_depth_test.py`investigates the trade-off between quantum circuit depth (complexity) and
# predictive performance. By increasing the number of repetitions ('reps') in the
# variational ansatz, we increase the model's capacity to learn complex functions,
# but also increase the difficulty of optimization (the "barren plateau" problem).

from utils import prepare_baltimore_qml_data
import numpy as np
import matplotlib.pyplot as plt
import os
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error

# Qiskit Imports
from qiskit.circuit.library import ZZFeatureMap, RealAmplitudes
from qiskit_machine_learning.algorithms import VQR
from qiskit_algorithms.optimizers import COBYLA
from qiskit.primitives import Estimator

def run_depth_analysis():
    print("--- Starting Quantum Circuit Depth Analysis ---")

    # Ensure output directory exists
    os.makedirs("baltimore-figures", exist_ok=True)

    # 1. Prepare Data
    # We use the same data pipeline as the main QML script to ensure consistency.
    X, y, _ = prepare_baltimore_qml_data()

    # Scale features and target to [0, 1] for quantum processing
    scaler_x = MinMaxScaler()
    X_scaled = scaler_x.fit_transform(X)

    scaler_y = MinMaxScaler()
    y_scaled = scaler_y.fit_transform(y.reshape(-1, 1)).flatten()

    # Split data (Fixed random_state=42 for reproducibility)
    X_train, X_test, y_train, y_test = train_test_split(
        X_scaled, y_scaled, test_size=0.2, random_state=42
    )

    # Store the actual (unscaled) test values for final error calculation
    y_test_actual = scaler_y.inverse_transform(y_test.reshape(-1, 1))

    # 2. Define Depths to Test
    # "Depth" here refers to the number of repetitions (reps) of the ansatz layers.
    # Depth 1 = Shallow (Less expressive, easier to train)
    # Depth 3 = Deep (More expressive, harder to train)
    depths = [1, 2, 3]
    mse_results = []

    num_features = X.shape[1]
    print(f"Features: {num_features} | Training Samples: {len(X_train)}")

    # 3. Training Loop
    for depth in depths:
        print(f"\n... Training VQR with Ansatz Depth (Reps) = {depth} ...")

        # Fixed Feature Map (same as main study)
        feature_map = ZZFeatureMap(feature_dimension=num_features, reps=1)

        # Variable Ansatz (this is what we are testing)
        ansatz = RealAmplitudes(num_qubits=num_features, reps=depth)

        # Optimizer
        optimizer = COBYLA(maxiter=300)

        # Instantiate VQR
        vqr = VQR(
            feature_map=feature_map,
            ansatz=ansatz,
            optimizer=optimizer,
            estimator=Estimator(),
        )

        # Train
        vqr.fit(X_train, y_train)

        # Predict
        y_pred_scaled = np.array(vqr.predict(X_test)).reshape(-1, 1)
        y_pred = scaler_y.inverse_transform(y_pred_scaled)

        # Calculate Error
        mse = mean_squared_error(y_test_actual, y_pred)
        mse_results.append(mse)
        print(f"   -> Completed. MSE: {mse:.4f}")

    # 4. Visualization
    print("\n--- Generating Depth vs. Performance Plot ---")

    plt.figure(figsize=(8, 5))
    plt.plot(depths, mse_results, marker='o', linestyle='-', color='#d62728', linewidth=2)

    plt.title("Impact of Quantum Circuit Depth on Prediction Error")
    plt.xlabel("Circuit Depth (Ansatz Repetitions)")
    plt.ylabel("Mean Squared Error (Lower is Better)")
    plt.xticks(depths)
    plt.grid(True, alpha=0.3)

    # Save figure
    out_path = "baltimore-figures/figure-depth-analysis.png"
    plt.savefig(out_path, dpi=300)
    print(f"Saved analysis plot to: {out_path}")

    # Print summary table
    print("\nSummary Results:")
    print("Depth | MSE")
    print("------|-------")
    for d, m in zip(depths, mse_results):
        print(f"  {d}   | {m:.4f}")

if __name__ == "__main__":
    run_depth_analysis()