# -*- coding: utf-8 -*-
"""baltimore_ml

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WNlkbv2hc-jrIHUSkihQf6L4pbAkdb84
"""

# `baltimore_ml.py` serves as the classical control group for our thesis
# experiment. Before we can claim any utility or feasibility for Quantum
# Machine Learning, we must establish a rigorous baseline using mature,
# classical algorithms. This script trains both a linear model (Linear
# Regression) and a non-linear ensemble model (Random Forest) on the exact same
# Baltimore data splits used by the quantum model.

from utils import init, prepare_baltimore_qml_data

import os
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error


# `train_classical_models` is the workhorse function. It performs the standard
# ML pipeline: scaling data, splitting into train/test sets, training multiple
# models, and collecting performance metrics.
def train_classical_models(X, y, test_size=0.2, random_state=42):
    """
    Train classical regression models (Linear Regression and Random Forest)
    to predict NO2 for Baltimore.

    Returns:
        Dictionary containing results for both models with:
        - trained model
        - predictions
        - metrics (MSE, R2, MAE)
    """
    print("--- Preparing data for Classical ML ---")

    # We scale the features to a [0, 1] range. While classical Random Forests
    # don't strictly require scaling, doing so ensures fair parity with the
    # quantum model (which requires scaled inputs for rotation gates).
    scaler_x = MinMaxScaler()
    X_scaled = scaler_x.fit_transform(X)

    # Similarly, we scale the target variable (NO2 levels).
    scaler_y = MinMaxScaler()
    y_scaled = scaler_y.fit_transform(y.reshape(-1, 1)).flatten()

    # We use a fixed `random_state` of 42. This is crucial for the thesis: it
    # guarantees that the classical model sees the exact same training examples
    # and test examples as the quantum model, making the comparison valid.
    X_train, X_test, y_train, y_test = train_test_split(
        X_scaled,
        y_scaled,
        test_size=test_size,
        random_state=random_state,
    )

    print(f"Number of training samples: {len(X_train)}")
    print(f"Number of test samples:     {len(X_test)}")
    print(f"Number of features:         {X.shape[1]}")

    results = {}

    # ========== Linear Regression ==========
    # First, we train a simple Linear Regression. This checks if the relationship
    # between HOLC grade/demographics and pollution is simple and linear.
    print("\n--- Training Linear Regression ---")
    lr_model = LinearRegression()
    lr_model.fit(X_train, y_train)

    # We predict on the test set and then inverse-transform the results so we
    # can interpret the error in real units (ppb) rather than scaled units.
    y_pred_lr_scaled = lr_model.predict(X_test).reshape(-1, 1)
    y_test_scaled = y_test.reshape(-1, 1)

    y_pred_lr = scaler_y.inverse_transform(y_pred_lr_scaled)
    y_test_actual = scaler_y.inverse_transform(y_test_scaled)

    # Calculate standard regression metrics.
    mse_lr = mean_squared_error(y_test_actual, y_pred_lr)
    r2_lr = r2_score(y_test_actual, y_pred_lr)
    mae_lr = mean_absolute_error(y_test_actual, y_pred_lr)

    print("Linear Regression Results (Baltimore NO2):")
    print(f"  Mean Squared Error:      {mse_lr:.4f}")
    print(f"  R2 Score:                {r2_lr:.4f}")
    print(f"  Mean Absolute Error:     {mae_lr:.4f}")

    results["linear_regression"] = {
        "model": lr_model,
        "y_pred": y_pred_lr,
        "y_test": y_test_actual,
        "mse": mse_lr,
        "r2": r2_lr,
        "mae": mae_lr,
    }

    # ========== Random Forest Regression ==========
    # Next, we train a Random Forest. This model can capture complex, non-linear
    # interactions between variables. It represents a "strong" classical baseline.
    print("\n--- Training Random Forest Regressor ---")
    rf_model = RandomForestRegressor(
        n_estimators=100,
        max_depth=10,
        random_state=random_state,
        n_jobs=-1,
    )
    rf_model.fit(X_train, y_train)

    y_pred_rf_scaled = rf_model.predict(X_test).reshape(-1, 1)
    y_pred_rf = scaler_y.inverse_transform(y_pred_rf_scaled)

    mse_rf = mean_squared_error(y_test_actual, y_pred_rf)
    r2_rf = r2_score(y_test_actual, y_pred_rf)
    mae_rf = mean_absolute_error(y_test_actual, y_pred_rf)

    print("Random Forest Results (Baltimore NO2):")
    print(f"  Mean Squared Error:      {mse_rf:.4f}")
    print(f"  R2 Score:                {r2_rf:.4f}")
    print(f"  Mean Absolute Error:     {mae_rf:.4f}")

    results["random_forest"] = {
        "model": rf_model,
        "y_pred": y_pred_rf,
        "y_test": y_test_actual,
        "mse": mse_rf,
        "r2": r2_rf,
        "mae": mae_rf,
    }

    return results, scaler_x, scaler_y


# `plot_classical_results` generates visual comparisons of the Actual vs.
# Predicted NO2 levels. If the models were perfect, all dots would lie exactly
# on the red dashed line. The spread of the dots indicates the variance and
# error of the model.
def plot_classical_results(results, out_dir="baltimore-figures"):
    os.makedirs(out_dir, exist_ok=True)

    fig, axes = plt.subplots(1, 2, figsize=(14, 6))

    models = [
        ("linear_regression", "Linear Regression", "royalblue"),
        ("random_forest", "Random Forest", "forestgreen"),
    ]

    for idx, (model_key, model_name, color) in enumerate(models):
        ax = axes[idx]
        y_test = results[model_key]["y_test"]
        y_pred = results[model_key]["y_pred"]
        r2 = results[model_key]["r2"]
        mse = results[model_key]["mse"]

        ax.scatter(y_test, y_pred, color=color, alpha=0.6, label="Census Blocks")

        # Visual guide for perfect prediction
        min_val = min(np.min(y_test), np.min(y_pred))
        max_val = max(np.max(y_test), np.max(y_pred))
        ax.plot(
            [min_val, max_val],
            [min_val, max_val],
            "r--",
            linewidth=1.5,
            label="Perfect Prediction",
        )

        ax.set_xlabel("Actual NO₂ (ppb)")
        ax.set_ylabel(f"Predicted NO₂ (ppb) – {model_name}")
        ax.set_title(f"{model_name}\nR² = {r2:.4f}, MSE = {mse:.4f}")
        ax.legend()
        ax.grid(True, alpha=0.3)

    plt.tight_layout()
    out_path = os.path.join(out_dir, "figure-bml-1.png")
    plt.savefig(out_path, dpi=300, bbox_inches="tight")
    plt.close()

    print(f"\nClassical ML prediction plots saved to {out_path}")


# `plot_comparison_table` creates a clean, publication-ready table of metrics.
# This makes it easy to compare the MSE, R2, and MAE of the two classical
# models side-by-side.
def plot_comparison_table(results, out_dir="baltimore-figures"):
    os.makedirs(out_dir, exist_ok=True)

    fig, ax = plt.subplots(figsize=(10, 3))
    ax.axis("tight")
    ax.axis("off")

    table_data = [
        ["Model", "MSE", "R² Score", "MAE"],
        [
            "Linear Regression",
            f"{results['linear_regression']['mse']:.4f}",
            f"{results['linear_regression']['r2']:.4f}",
            f"{results['linear_regression']['mae']:.4f}",
        ],
        [
            "Random Forest",
            f"{results['random_forest']['mse']:.4f}",
            f"{results['random_forest']['r2']:.4f}",
            f"{results['random_forest']['mae']:.4f}",
        ],
    ]

    table = ax.table(
        cellText=table_data,
        cellLoc="center",
        loc="center",
        colWidths=[0.3, 0.2, 0.2, 0.2],
    )

    table.auto_set_font_size(False)
    table.set_fontsize(11)
    table.scale(1, 2)

    # Apply styling to make the table look professional (header colors, etc.)
    for i in range(4):
        table[(0, i)].set_facecolor("#4472C4")
        table[(0, i)].set_text_props(weight="bold", color="white")

    for i in range(1, 3):
        color = "#D9E1F2" if i % 2 == 0 else "white"
        for j in range(4):
            table[(i, j)].set_facecolor(color)

    plt.title(
        "Classical ML Performance: Baltimore NO₂ Prediction",
        fontsize=14,
        weight="bold",
        pad=20,
    )

    out_path = os.path.join(out_dir, "figure-bml-comparison.png")
    plt.savefig(out_path, dpi=300, bbox_inches="tight")
    plt.close()

    print(f"Comparison table saved to {out_path}")


# `print_feature_importance` allows us to look inside the "black box" of the
# Random Forest. It tells us which variables (HOLC Grade vs Demographics) were
# most influential in predicting pollution levels.
def print_feature_importance(results):
    rf_model = results["random_forest"]["model"]
    feature_names = ["HOLC Grade", "% Black", "% White"]

    print("\n--- Random Forest Feature Importance ---")
    importances = rf_model.feature_importances_
    for name, importance in zip(feature_names, importances):
        print(f"  {name:15s}: {importance:.4f}")


if __name__ == "__main__":
    print("=" * 60)
    print("CLASSICAL ML BASELINE FOR BALTIMORE NO2 PREDICTION")
    print("=" * 60)

    # 1. Load and prep the data.
    X, y, baltimore_df = prepare_baltimore_qml_data()

    # 2. Train the baseline models.
    results, scaler_x, scaler_y = train_classical_models(X, y)

    # 3. Generate the analysis figures.
    plot_classical_results(results)
    plot_comparison_table(results)
    print_feature_importance(results)

    print("\n" + "=" * 60)
    print("SUMMARY")
    print("=" * 60)
    print(
        f"Linear Regression - R²: {results['linear_regression']['r2']:.4f}, "
        f"MSE: {results['linear_regression']['mse']:.4f}"
    )
    print(
        f"Random Forest     - R²: {results['random_forest']['r2']:.4f}, "
        f"MSE: {results['random_forest']['mse']:.4f}"
    )
    print("\nCompare these results with baltimore_qml.py to evaluate")
    print("whether quantum machine learning provides advantages for this task.")
    print("=" * 60)