# -*- coding: utf-8 -*-
"""utils

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WNlkbv2hc-jrIHUSkihQf6L4pbAkdb84
"""

# `utils.py` contains utility functions used by scripts to collect and organize
# data and subsequently generate plots of different variations. There is a lot
# of repetition in how some of these plots are generated, so many functions
# were abstracted here to improve readability.

# Necessary imports.
import csv
import pandas as pd
import numpy as np

# `init()` takes the raw data file referenced in the study (see `README`) and
# generates and returns a pandas DataFrame for further analysis.
def init():
   data = []
   with open('HOLC.all.20220304.csv') as input:
      for line in csv.DictReader(input, fieldnames = ('num',
                                                      'CUA',
                                                      'City',
                                                      'GEOID',
                                                      'grade',
                                                      'PHOLC',
                                                      'asian',
                                                      'black',
                                                      'hispanic',
                                                      'white',
                                                      'other',
                                                      'total',
                                                      'no2',
                                                      'pm25')):
         data.append(line)

   # Discard the first field, `num`.
   data.pop(0)

   # Initialize lists to store all other fields of interest...
   cua      = []
   city     = []
   geo_id   = []
   grade    = []
   pholc    = []
   asian    = []
   black    = []
   hispanic = []
   white    = []
   other    = []
   total    = []
   no2      = []
   pm25     = []

   # ...and add the data to the appropriate ones.
   for entry in data:
      cua.append(entry['CUA'])
      city.append(entry['City'])
      geo_id.append(entry['GEOID'])
      grade.append(entry['grade'])
      pholc.append(entry['PHOLC'])
      asian.append(entry['asian'])
      black.append(entry['black'])
      hispanic.append(entry['hispanic'])
      white.append(entry['white'])
      other.append(entry['other'])
      total.append(entry['total'])
      no2.append(entry['no2'])
      pm25.append(entry['pm25'])

   df = pd.DataFrame({
      "CUA"      : cua,
      "City"     : city,
      "GEOID"    : geo_id,
      "Grade"    : grade,
      "PHOLC"    : pholc,
      "Asian"    : asian,
      "Black"    : black,
      "Hispanic" : hispanic,
      "White"    : white,
      "Other"    : other,
      "Total"    : total,
      "NO2"      : no2,
      "PM25"     : pm25
   })

   # Convert numerical field values to numbers
   df['PHOLC']    = pd.to_numeric(df['PHOLC'])
   df['Asian']    = pd.to_numeric(df['Asian'])
   df['Black']    = pd.to_numeric(df['Black'])
   df['Hispanic'] = pd.to_numeric(df['Hispanic'])
   df['White']    = pd.to_numeric(df['White'])
   df['Other']    = pd.to_numeric(df['Other'])
   df['Total']    = pd.to_numeric(df['Total'])
   df['NO2']      = pd.to_numeric(df['NO2'])
   df['PM25']     = pd.to_numeric(df['PM25'])

   return df

# `calc_city_pwm` is a function that calculates and returns the population-weighted
# mean level of the given datapoint for that city.
def calc_city_pwm(target_city, all_cities, datapoint, population):
   condition = ((all_cities == target_city) & (~np.isnan(datapoint)) &
                (~np.isnan(population)))
   datapoint = datapoint[condition]
   population = population[condition]
   return np.average(datapoint, weights = population)

# `collect_data` creates and returns a list containing NO₂ and PM₂.₅ levels
# organized by HOLC grade and demographics.
def collect_data(df, population_factor, target_data, calc_diff):
   HOLC_A_data = []
   HOLC_B_data = []
   HOLC_C_data = []
   HOLC_D_data = []
   white       = []
   other       = []
   black       = []
   asian       = []
   hispanic    = []

   diff = "0"
   if calc_diff:
      cities = list(set(df['City']))
      pwms = {}
      for city in cities:
         pwms[city] = calc_city_pwm(city, df['City'], df[target_data], df['Total'])
      diff = "pwms[df['City'][i]]"

   for i in df.index:
      datapoint = [(df[target_data][i]) - eval(diff)]
      if df['Grade'][i] == 'A':
         HOLC_A_data += (round(df[population_factor][i] * df['Total'][i]) * datapoint)
      if df['Grade'][i] == 'B':
         HOLC_B_data += (round(df[population_factor][i] * df['Total'][i]) * datapoint)
      if df['Grade'][i] == 'C':
         HOLC_C_data += (round(df[population_factor][i] * df['Total'][i]) * datapoint)
      if df['Grade'][i] == 'D':
         HOLC_D_data += (round(df[population_factor][i] * df['Total'][i]) * datapoint)
      if df['Grade'][i] != 'N':
         white += (round(df[population_factor][i] * df['White'][i]) * datapoint)
         other += (round(df[population_factor][i] * df['Other'][i]) * datapoint)
         black += (round(df[population_factor][i] * df['Black'][i]) * datapoint)
         asian += (round(df[population_factor][i] * df['Asian'][i]) * datapoint)
         hispanic += (round(df[population_factor][i] * df['Hispanic'][i]) * datapoint)

   return [HOLC_A_data, HOLC_B_data, HOLC_C_data, HOLC_D_data, white, other,
           black, asian, hispanic]

# `collect_data_intraurban_diff` creates and returns lists representing the
# intraurban difference in air pollutant level for listed demographics.
def collect_data_intraurban_diff(df, population_factor, target_data):
   def collect_demographic_data(df, population_factor, population, target_data, pwms):
      A_data = []
      B_data = []
      C_data = []
      D_data = []
      for i in df.index:
         datapoint = (round(df[population_factor][i] * df[population][i]) *
                      [df[target_data][i] - pwms[df['City'][i]]])
         if df['Grade'][i] == 'A':
            A_data += datapoint
         if df['Grade'][i] == 'B':
            B_data += datapoint
         if df['Grade'][i] == 'C':
            C_data += datapoint
         if df['Grade'][i] == 'D':
            D_data += datapoint
      return [np.average(A_data), np.average(B_data), np.average(C_data), np.average(D_data)]

   cities = list(set(df['City']))
   pwms = {}
   for city in cities:
      pwms[city] = calc_city_pwm(city, df['City'], df[target_data], df['Total'])

   hispanic = collect_demographic_data(df, population_factor, 'Hispanic', target_data, pwms)
   asian = collect_demographic_data(df, population_factor, 'Asian', target_data, pwms)
   black = collect_demographic_data(df, population_factor, 'Black', target_data, pwms)
   total = collect_demographic_data(df, population_factor, 'Total', target_data, pwms)
   white = collect_demographic_data(df, population_factor, 'White', target_data, pwms)
   return [hispanic, asian, black, total, white]

# `collect_data_residents` returns population totals and percentages per HOLC grade.
def collect_data_residents(df, population_factor, divisor):
   def collect_demographic_data(df, population_factor, residents, index, grade):
      residents[0][grade] += (round(df[population_factor][index] * df['White'][index]))
      residents[1][grade] += (round(df[population_factor][index] * df['Other'][index]))
      residents[2][grade] += (round(df[population_factor][index] * df['Black'][index]))
      residents[3][grade] += (round(df[population_factor][index] * df['Asian'][index]))
      residents[4][grade] += (round(df[population_factor][index] * df['Hispanic'][index]))

   def adjust_numerical_data(lst, divisor):
      res = []
      for sublist in lst: res.append([x / divisor for x in sublist])
      return res

   def compute_percentages(lst, totals):
      res = []
      for elem, total in zip(lst, totals): res.append((elem / total) * 100)
      return res

   white = [0] * 4
   other = [0] * 4
   black = [0] * 4
   asian = [0] * 4
   hispanic = [0] * 4
   residents = [white, other, black, asian, hispanic]

   for i in df.index:
      if df['Grade'][i] == 'A':
         collect_demographic_data(df, population_factor, residents, i, 0)
      if df['Grade'][i] == 'B':
         collect_demographic_data(df, population_factor, residents, i, 1)
      if df['Grade'][i] == 'C':
         collect_demographic_data(df, population_factor, residents, i, 2)
      if df['Grade'][i] == 'D':
         collect_demographic_data(df, population_factor, residents, i, 3)

   numerical_data = adjust_numerical_data(residents, divisor)
   A_total = sum(lst[0] for lst in residents)
   B_total = sum(lst[1] for lst in residents)
   C_total = sum(lst[2] for lst in residents)
   D_total = sum(lst[3] for lst in residents)
   totals = [A_total, B_total, C_total, D_total]
   percentage_data = [compute_percentages(population, totals) for population in residents]

   return numerical_data, percentage_data

# `collect_data_percentile` returns cumulative distribution of air pollutants.
def collect_data_percentile(df, population_factor, population, target_data):
   percentile_A = []
   percentile_B = []
   percentile_C = []
   percentile_D = []
   cumulative = []
   percentiles = range(0, 100)

   for i in df.index:
      datapoint = (round(df[population_factor][i] * df[population][i]) * [df[target_data][i]])
      cumulative += datapoint
      if df['Grade'][i] == 'A':
         percentile_A += datapoint
      if df['Grade'][i] == 'B':
         percentile_B += datapoint
      if df['Grade'][i] == 'C':
         percentile_C += datapoint
      if df['Grade'][i] == 'D':
         percentile_D += datapoint

   return (np.percentile(percentile_A, percentiles), np.percentile(percentile_B, percentiles),
           np.percentile(percentile_C, percentiles), np.percentile(percentile_D, percentiles),
           np.percentile(cumulative, percentiles))

# `collect_data_city` returns distribution of air pollutant separated by city size.
def collect_data_city(df, population_factor, population, target_data, calc_diff, calc_per):
   def calc_city_pop(target_city, all_cities, grade, population_factor, population):
      condition = ((all_cities == target_city) & (~np.equal(grade, 'N')))
      population_factor = population_factor[condition]
      population = population[condition]
      return sum(round(population_factor * population))

   def sort_city_pops(city_pops, sorted_populations):
      small_cities = []
      medium_cities = []
      large_cities = []
      for i in range(0, 173):
         small_cities.append(list(city_pops.keys())[list(city_pops.values()).index(sorted_populations[i])])
      for i in range(173, 194):
         medium_cities.append(list(city_pops.keys())[list(city_pops.values()).index(sorted_populations[i])])
      for i in range(194, 202):
         large_cities.append(list(city_pops.keys())[list(city_pops.values()).index(sorted_populations[i])])
      return small_cities, medium_cities, large_cities

   def collect_city_measurements(target_city, target_grade, cities, lst, datapoint):
      if target_city in cities:
         if target_grade == 'A':
            lst[0] += datapoint
         if target_grade == 'B':
            lst[1] += datapoint
         if target_grade == 'C':
            lst[2] += datapoint
         if target_grade == 'D':
            lst[3] += datapoint

   def adjust_percentages(lst):
      res = []
      for sublist in lst: res.append([x * 100 for x in sublist])
      return res

   cities = set(df['City'])
   cities.remove('NA')
   city_pops = {}
   diff = "0"
   for city in cities:
      city_pops[city] = calc_city_pop(city, df['City'], df['Grade'],
                                      df[population_factor], df[population])

   if calc_diff:
      pwms = {}
      for city in cities:
         pwms[city] = calc_city_pwm(city, df['City'], df[target_data], df[population])
      diff = "pwms[df['City'][i]]"

   sorted_populations = list(city_pops.values())
   sorted_populations.sort()
   small_cities, medium_cities, large_cities = sort_city_pops(city_pops, sorted_populations)

   small_city_data  = [[], [], [], []]
   medium_city_data = [[], [], [], []]
   large_city_data  = [[], [], [], []]

   per = "1"
   if calc_per:
      per = "pwms[df['City'][i]]"

   for i in df.index:
      if df['City'][i] != 'NA':
         datapoint = (round(df[population_factor][i] * df[population][i]) *
                      [((df[target_data][i]) - eval(diff)) / eval(per)])
         collect_city_measurements(df['City'][i], df['Grade'][i], small_cities,
                                   small_city_data, datapoint)
         collect_city_measurements(df['City'][i], df['Grade'][i], medium_cities,
                                   medium_city_data, datapoint)
         collect_city_measurements(df['City'][i], df['Grade'][i], large_cities,
                                   large_city_data, datapoint)

   if calc_per:
      small_city_data = adjust_percentages(small_city_data)
      medium_city_data = adjust_percentages(medium_city_data)
      large_city_data = adjust_percentages(large_city_data)

   small_city_data = [np.average(x) for x in small_city_data]
   medium_city_data = [np.average(x) for x in medium_city_data]
   large_city_data = [np.average(x) for x in large_city_data]

   return [small_city_data, medium_city_data, large_city_data]

# `prepare_baltimore_qml_data` is the critical bridge between the raw national
# data and our machine learning models. It loads the full dataset using
# `init()`, but then performs a series of filtering and cleaning steps to isolate
# only the Baltimore, MD data. Crucially, unlike the descriptive statistics
# generated in `baltimore.py`, this function does *not* explode the data by
# population counts (i.e., duplicating rows). Instead, it treats each census
# block as a unique training sample, which is the standard requirement for
# regression tasks in machine learning.
def prepare_baltimore_qml_data():
   df = init()

   # We must verify that the dataset contains every column we plan to use for
   # feature engineering. If the CSV format changes in the future, this check
   # will alert us immediately.
   required_cols = [
      "City", "Grade", "PHOLC",
      "Asian", "Black", "Hispanic", "White", "Other", "Total",
      "NO2", "PM25",
   ]
   missing = [c for c in required_cols if c not in df.columns]
   if missing:
      raise ValueError(f"Missing required columns in DataFrame: {missing}")

   # Isolate data for Baltimore, MD.
   baltimore_df = df[df["City"] == "Baltimore, MD"].copy()

   # We drop any rows that are missing key demographic or pollution data, as
   # machine learning models generally cannot handle NaN values without specific
   # imputation strategies.
   baltimore_df = baltimore_df.dropna(
      subset=[
         "NO2", "Grade",
         "Asian", "Black", "Hispanic", "White", "Other", "Total",
      ]
   )

   # We also remove any blocks that were not assigned a standard HOLC grade
   # (marked as 'N'), as these cannot be encoded ordinally.
   baltimore_df = baltimore_df[baltimore_df["Grade"] != "N"].copy()

   # Feature Engineering: Convert raw population counts into percentages. This
   # normalizes the data, ensuring that the *proportion* of a demographic is
   # the feature, rather than the raw magnitude of the population.
   baltimore_df["Pct_White"] = baltimore_df["White"] / baltimore_df["Total"]
   baltimore_df["Pct_Black"] = baltimore_df["Black"] / baltimore_df["Total"]
   baltimore_df["Pct_Asian"] = baltimore_df["Asian"] / baltimore_df["Total"]
   baltimore_df["Pct_Hispanic"] = (
      baltimore_df["Hispanic"] / baltimore_df["Total"]
   )

   # To make the categorical HOLC grades usable by our mathematical models, we
   # map them to an ordinal scale: A (Best) = 1, D (Worst) = 4. This preserves
   # the inherent ranking of the redlining grades.
   grade_map = {"A": 1, "B": 2, "C": 3, "D": 4}
   baltimore_df["Grade_Encoded"] = baltimore_df["Grade"].map(grade_map)

   # One final check to ensure our mapping didn't produce any null values.
   baltimore_df = baltimore_df.dropna(subset=["Grade_Encoded"])

   # We select a compact feature set (Grade, % Black, % White) to keep the
   # quantum circuit depth manageable.
   feature_cols = ["Grade_Encoded", "Pct_Black", "Pct_White"]
   target_col = "NO2"

   X = baltimore_df[feature_cols].values
   y = baltimore_df[target_col].values

   return X, y, baltimore_df